dfinity/repositories-open-to-contributions

.github/actions/get_repo_name/action.yml
.github/workflows/check_new_repo.yml
open-repositories.txt

This workflow will only run in the current repository and check if any repositories added to the list meet the compliance checks. It does this by checking the most recent commit changes to `open-repositories.txt` file.
For a demo of how the workflow is activated, see the following PR: https://github.com/dfinity/repositories-open-to-contributions/pull/35

add workflow for new repo

---

.github/actions/check_external_contrib/action.yml
custom_python_actions/check_external_contrib.py
requirements.in
requirements.txt
tests/test_check_external_contrib.py

Instead of using the github api to get the contents of the file `open-reposotories.txt` I discovered that the `github3` python package has the same functionality. This simplifies the code a little and is more consistent with how we interact with github in other modules.

use github3 package instead of github

---

open-repositories.txt

The repository was never published and now archived.

Remove capsules from open-repositories

---

.github/workflows/check_cla.yml

This fixes a bug I didn't notice before. Prior to this change this was the workflow execution:
Where `Check CLA` was run because there was no output for `is_member`. This change results in the correct execution of the workflow:

fix workflow

---

.github/workflows/check_cla.yml

Because this workflow will be used as a required workflow, we need to pass in the repository it needs to check out.

specify repo to check out

---

.github/workflows/check_cla.yml

Intended behavior was to have the cla workflow triggered by `pull_request` run on internal PRs and `pull_request_target` run on forked PRs, but this adds a lot of complexity and did not work as expected.
The simplest solution is to only use `pull_request_target` which runs on master and manually kick off the workflow (for internal developers) when updates to the cla workflow need to be made and tested.

remove pull_request trigger

---

.github/workflows/check_cla.yml

I need to test this out a little more, but I think removing this line broke the required workflows for regular internal PRs. It might be necessary to have separate workflows for external and internal contributions, but right now I just want to test if adding these lines back fixes required workflows.

add regular pull_request trigger

---

.github/custom_python_actions/check_cla_issue.py
.github/custom_python_actions/check_cla_pr.py
.github/custom_python_actions/check_compliance.py
.github/custom_python_actions/check_external_contrib.py
.github/custom_python_actions/check_membership.py
.github/tests/test_check_external_contrib.py
.github/tests/test_cla_issue.py
.github/tests/test_cla_pr.py
.github/tests/test_membership.py
.gitignore

Github actions doesn't indicate when a secret doesn't exist, it just passes in an empty env var. We therefore need to have explicit error handling to avoid confusing error messages.

Improve error message

---

.github/workflows/check_cla.yml

There were some issues where repositories using this required workflow were referencing incorrect PR numbers (those from repositories-open-to-contributions and not the relevant repos). This change ensures that the workflow is run on the external repos and only code for running the actions is used from `repositories-open-to-contributions`.

Fix pr closing workflow

---

.github/actions/check_membership/action.yml
.github/workflows/check_cla.yml

It defaults to whichever actor pushed the most recent commit, but we want the actor who opened the PR.

update actor to pull_request opened

---

.github/actions/check_membership/action.yml
.github/workflows/check_cla.yml

Unfortunately this is a little more complicated. For the custom actions we need to check out `repositories-open-to-contributions` since it also needs to run custom python scripts it won't have access to otherwise. But for closing the PR we need to check out the repository where the PR needs to be closed. I will need to test this out a little more.

check out different repo for each step in CLA

---

.github/workflows/check_cla.yml

It's a little more intuitive for this to be too separate jobs:
1) Check membership of the contributor
2) Workflow for external contributors
It also simplifies the conditional if logic.

break into separate jobs

---

open-repositories.txt

Add `test-compliant-repository-public` to accepts-external-contributions list so we can test the CLA workflow for external contributions.

add test-compliant-repository-public

---

.github/workflows/check_cla.yml

Otherwise it's status is not reported and merge fails: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

CLA workflow has to run in the merge queue.

---

.github/workflows/check_cla.yml

Disable merge group as `pull_request` blocks PRs from external contributors. Need to test this more.

disable merge group

---

open-repositories.txt

Need to test something and temporarily disable external contributions - this repo is only used for internal testing.

remove test-compliant-repository-public

---

open-repositories.txt

We'd like to open up the [cycles ledger repository](https://github.com/dfinity/cycles-ledger) for external contributions.

feat: [IC-1636] Adding the cycles ledger repository

---

open-repositories.txt

Reverts dfinity/repositories-open-to-contributions#352
My apologies @ielashi, I didn't realize this hadn't been published yet. Accepting external contributions should be done after the repo has gone through the review process.

Revert "mark 'bench' repo open to external contributions"

---

.github/custom_python_actions/check_compliance.py
.github/custom_python_actions/compliance_checks.py
.github/tests/test_compliance_checks.py

Now that we have branch protections enabled by default on the `dfinity` org we don't need to check for them anymore. This will eliminate any potential errors when they have been configured by rulesets instead of traditional branch protections.

chore(IDX): remove branch protections check

---

open-repositories.txt

The `new-motoko-base` repository was recently renamed to `motoko-core`.

Replace `new-motoko-base` with `motoko-core`

---

LICENSE

This PR removes the modified appendix from the LICENSE file to ensure full compliance with the Apache 2.0 license, which should remain in its original, unmodified form. This change aligns our repositories with standard practices for license documentation.

Clean up LICENSE file by removing boilerplate text
