open-repositories.txt

Related Jira ticket: https://dfinity.atlassian.net/browse/IC-1244

IC-1244: open rules_motoko repo for contributions

---

open-repositories.txt

would like to add https://github.com/dfinity/wg-identity-authentication

adding repository

---

open-repositories.txt

Approvals for opensourcing: https://dfinity.atlassian.net/browse/IC-1442

Add metrics-encoder repo

---

open-repositories.txt

The [exchange rate canister](https://github.com/dfinity/exchange-rate-canister) should be open to external contributions.

Adding the exchange rate canister

---

open-repositories.txt

Following the preparation instructions

Add ic-docutrack to accept external contributions

---

open-repositories.txt

This is a temporary removal until we figure out how to make the cla bot work with github merge queues

Remove Internet Identity

---

.github/actions/get_repo_name/action.yml
.github/workflows/check_new_repo.yml
custom_python_actions/check_compliance.py
custom_python_actions/check_external_contrib.py
open-repositories.txt
tests/test_check_external_contrib.py

Actually merge code into master.
"The bug" was that I previously only merged my branch of code into another branch, not master. 🤦‍♀️

New repo workflow

---

tests/test_check_compliance.py

While looking into how to do integration tests, I noticed that I was missing one small test.

Add branch protection test

---

.github/workflows/check_new_repo.yml

Forgot to add `has_permissions` as an output, which is why it was failing, but since I am refactoring this anyways, it's easier to remove this step and unblock the other PR.

remove check permissions step

---

.github/actions/get_repo_name/action.yml

Otherwise already existing repositories like `motoko` also match those that contains this work like `motoko-base`.

Full string comparison to detect new repository.

---

.github/actions/check_cla_issue/action.yml
.github/actions/check_cla_pr/action.yml
.github/custom_python_actions/check_cla_issue.py
.github/custom_python_actions/check_cla_pr.py
.github/tests/test_cla_issue.py
.github/tests/test_cla_pr.py
.github/workflows/check_cla.yml

This PR creates a separate action that can be called from a workflow located in the CLA repository. This will enable a better user experience, so that issues are immediately approved or declined when a user signs the CLA.

Idx 2846 refactor code trigger workflow based on issues

---

.github/actions/check_cla_issue/action.yml
.github/workflows/integration_tests.yml

Two small fixes:
- update github token permissions
- update integration test logic

Small fixes

---

.github/workflows/check_cla.yml
.github/workflows/integration_tests.yml

This PR closes a PR if the user is not a member and the repository is not accepting external contributions. See below for example messages.

add step to close PR

---

open-repositories.txt

add wasmtime-hs to open-repositories.txt

---

open-repositories.txt

IC-1549 publish ic-websocket-poc

add ic-websocket-poc open-repositories.txt

---

.github/custom_python_actions/check_membership.py
.github/tests/test_membership.py
.github/workflows/check_cla.yml

Small updates to enable running the cla workflow from a fork. This may require some trial and error, since I can only test this once it has been merged to master.

Modifications for external contributor

---

.github/custom_python_actions/check_membership.py
.github/tests/test_membership.py
.github/workflows/check_cla.yml

Fix: add logic to allow commits from dependobot(https://github.com/dfinity/repositories-open-to-contributions/pull/283)

Add member exemptions

---

.github/workflows/check_cla.yml

Was using incorrect worfklow syntax, docs here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts

fix workflow syntax

---

.github/custom_python_actions/check_cla_pr.py
.github/tests/test_cla_pr.py

This PR makes a slight improvement to the existing CLA workflow. Previously, the bot would only comment on the first PR that a new contributor opened. If they failed to sign the CLA, but opened another PR, the PR would not be mergeable, but would not explain why. This change enables the bot to create a comment on every PR from an external contributor who has not yet signed the CLA agreement.

Update cla workflow

---

.github/custom_python_actions/check_cla_pr.py
.github/tests/test_cla_pr.py

Shouldn't matter too much, but just to be on the safe side we should check that the issue was actually created by the bot.

check username for issue created

---

.github/workflows/check_cla.yml

The current configuration still does not trigger requried workflow on merge queue.

[IDX-2986] Try to trigger CLA on all pull requests.

---

open-repositories.txt

Jira ticket: [IC-1612](https://dfinity.atlassian.net/browse/IC-1612)
[IC-1612]: https://dfinity.atlassian.net/browse/IC-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `ic-eth-starter` to open repositories

---

.github/workflows/check_cla.yml

This might help with getting the merge queue unstuck, but I'm not sure.

Exclude github api bot

---

open-repositories.txt

https://github.com/dfinity/journald-parser/blob/main/CONTRIBUTING.md

[IC-1611] journald-parser to accept external contributions.

---

open-repositories.txt

Context: https://github.com/dfinity/motoko.rs/pull/181.

Add `dfinity/motoko.rs` to open repositories

---

open-repositories.txt

See accompanying ticket: https://dfinity.atlassian.net/browse/IC-1707

feat: add canbench to repos accepting external contributions

---

open-repositories.txt

In preparation for open sourcing it.

Update open-repositories.txt to accept contributions to ic-observability-stack.

---

.gitignore

I don't want to see the configuration of my editor listed as potential changes to be added to this repository.
- Add commonly ignored `.vscode` and `.idea` to the list of `.gitignore`

chore: .gitignore vscode and jetbrains config

---

open-repositories.txt

Open-sourcing ticket pending approvals: https://dfinity.atlassian.net/browse/IC-1779

feat: add internet-identity-playwright to open repos

---

open-repositories.txt

Open-sourcing ticket pending approvals: https://dfinity.atlassian.net/browse/IC-1778

feat: Add ic-canister-sig-creation to open repos

---

open-repositories.txt

Open-sourcing ticket pending approvals: https://dfinity.atlassian.net/browse/IC-1785

feat: Add ic-burp-extension to open repos

---

open-repositories.txt

This library has been extracted from Orbit.

Add canfund library

---

open-repositories.txt

Unblocks the following community contribution: https://github.com/dfinity/node-motoko/pull/113.

Add `node-motoko` to open repositories

---

open-repositories.txt

https://dfinity.atlassian.net/browse/IC-1962
[Slack thread](https://dfinity.slack.com/archives/C01PZCB2T2N/p1759138532404839)

chore: transfer mops repos to the dfinity org
